# Generated by Django 5.2.8 on 2025-12-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.CharField(blank=True, max_length=255, verbose_name='نص الإعلان')),
                ('is_announcement_active', models.BooleanField(default=False, verbose_name='تفعيل الإعلان؟')),
            ],
        ),
        migrations.AlterField(
            model_name='weeklylesson',
            name='day_of_week',
            field=models.CharField(max_length=20, verbose_name='اليوم'),
        ),
        migrations.AlterField(
            model_name='weeklylesson',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط؟'),
        ),
        migrations.AlterField(
            model_name='weeklylesson',
            name='lesson_title',
            field=models.CharField(max_length=200, verbose_name='عنوان الدرس'),
        ),
        migrations.AlterField(
            model_name='weeklylesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='weeklylesson',
            name='time_description',
            field=models.CharField(max_length=100, verbose_name='التوقيت'),
        ),
    ]
