# Generated by Django 5.2.8 on 2025-11-19 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('memorization', 'حفظ جديد'), ('review', 'مراجعة')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity_description', models.CharField(max_length=255)),
                ('self_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuranStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_id', models.IntegerField()),
                ('surah_name', models.CharField(max_length=100)),
                ('ayah_id', models.IntegerField()),
                ('ayah_text', models.TextField()),
                ('juz', models.IntegerField()),
                ('hizb', models.IntegerField()),
                ('rub', models.IntegerField()),
                ('thumn', models.IntegerField()),
                ('page', models.IntegerField()),
            ],
            options={
                'unique_together': {('surah_id', 'ayah_id')},
            },
        ),
        migrations.CreateModel(
            name='ThumnProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juz', models.IntegerField(verbose_name='الجزء')),
                ('hizb', models.IntegerField(verbose_name='الحزب')),
                ('thumn', models.IntegerField(verbose_name='رقم الثمن في الحزب')),
                ('status', models.CharField(choices=[('memorized', 'تم الحفظ'), ('reviewing', 'جاري المراجعة')], default='memorized', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumn_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['juz', 'hizb', 'thumn'],
                'unique_together': {('user', 'juz', 'hizb', 'thumn')},
            },
        ),
    ]
