# Generated by Django 5.2.8 on 2025-12-18 14:06

import django.core.validators
import django.db.models.deletion
import reviews.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecitationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=reviews.models.recitation_upload_path, verbose_name='ملف التلاوة')),
                ('surah_name', models.CharField(max_length=100, verbose_name='اسم السورة')),
                ('from_ayah', models.IntegerField(verbose_name='من الآية')),
                ('to_ayah', models.IntegerField(verbose_name='إلى الآية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'جاري الاستماع'), ('completed', 'تم التصحيح'), ('rejected', 'مرفوض/إعادة')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('instructor_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم (من 5)')),
                ('instructor_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات نصية')),
                ('instructor_audio', models.FileField(blank=True, null=True, upload_to=reviews.models.feedback_upload_path, verbose_name='تسجيل المشرف (رد صوتي)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التصحيح')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب تصحيح تلاوة',
                'verbose_name_plural': 'طلبات تصحيح التلاوة',
                'ordering': ['-created_at'],
            },
        ),
    ]
