# Generated by Django 5.2.8 on 2025-11-24 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbadge',
            options={},
        ),
        migrations.AlterField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(choices=[('first_thumn', 'أول ثمن محفوظ'), ('first_hizb', 'أول حزب كامل'), ('count_5_thumns', 'حفظ 5 أثمان')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0, verbose_name='مجموع نقاط الخبرة')),
                ('level', models.IntegerField(default=1, verbose_name='المستوى الحالي')),
                ('initial_memorization_thumns', models.IntegerField(default=0, verbose_name='رصيد الحفظ السابق (أثمان)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
