# Generated by Django 5.2.8 on 2025-11-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_userbadge_options_alter_badge_condition_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(choices=[('first_thumn', 'بداية الغيث (أول ثمن)'), ('first_hizb', 'رائحة الفجر (أول حزب)'), ('hizb_3', 'خطوة السائر (3 أحزاب)'), ('hizb_5', 'همة عالية (5 أحزاب)'), ('hizb_7', 'زاد المسافر (7 أحزاب)'), ('hizb_10', 'نفس المجتهد (10 أحزاب)'), ('hizb_15', 'ربع القرآن (15 حزب)'), ('hizb_20', 'عزيمة لا تلين (20 حزب)'), ('hizb_30', 'نصف القرآن (30 حزب)'), ('hizb_60', 'تاج الحافظ (الختمة)'), ('juz_amma', 'نور عم (جزء 30)'), ('juz_tabarak', 'تبارك البركة (جزء 29)'), ('surah_mulk', 'المُنجيَة (سورة الملك)'), ('surah_yasin', 'القلب الحي (سورة يس)'), ('surah_baqarah', 'سيدة السور (سورة البقرة)'), ('surah_rahman', 'درر الرحمن (سورة الرحمن)'), ('surah_kahf', 'نور الكهف (سورة الكهف)'), ('streak_7', 'خطوة كل يوم (7 أيام)'), ('streak_30', 'طريق النور (30 يوم)'), ('streak_100', 'روح المثابر (100 يوم)')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon_name',
            field=models.CharField(help_text='اسم الأيقونة (مثال: star, award, crown)', max_length=50),
        ),
    ]
