# Generated by Django 5.2.8 on 2025-11-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_alter_badge_condition_type_alter_badge_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationprofile',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='أيام المداومة الحالية'),
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر نشاط'),
        ),
    ]
