# Generated by Django 5.2.8 on 2025-11-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_gamificationprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamificationprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='الصورة الشخصية'),
        ),
    ]
