# Generated by Django 5.2.8 on 2025-11-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_gamificationprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamificationprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='daily_goal',
            field=models.CharField(choices=[('thumn', 'ثمن واحد/يوم'), ('rub', 'ربع حزب/يوم'), ('page', 'صفحة/يوم')], default='thumn', max_length=20, verbose_name='الهدف اليومي'),
        ),
        migrations.AlterField(
            model_name='gamificationprofile',
            name='initial_memorization_thumns',
            field=models.IntegerField(default=0, verbose_name='رصيد الحفظ السابق'),
        ),
    ]
